
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhzcpcdygnqetrkjwtco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoemNwY2R5Z25xZXRya2p3dGNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMDY1NzgsImV4cCI6MjA1OTY4MjU3OH0.rgzwcex8q20cHgs18ZzHWykenxxJrOrGqA_el3OL24Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
